#%RAML 1.0 DataType

#This file is located at dataTypes/primitives/decimal.raml

type: number
description: |
  A JSON number, except that exponents are not allowed or xs:decimal, except that decimals may not use exponents, and leading 0 digits are not allowed
