#%RAML 1.0 DataType

#This file is located at dataTypes/primitives/markdown.raml

type: string
description: A string that may contain markdown syntax for optional processing by a markdown presentation engine
