language: node_js
node_js:
- '6'
sudo: required
services:
- docker

env:
  global:
  - DOCKER_IMAGE_REPO: CURE
    PROJECT_NAME: hospitalrun

before_install:
- chmod +x conf/*.sh

cache:
  directories:
  - "$HOME/.cache"
  - "$hOME/.npm"

script:
- echo "No test scripts! Developers should create test scripts to be run here"

deploy:
- provider: script
  script: "./conf/travis-deploy.sh"
  skip_cleanup: true
  on:
    branch: master