#%RAML 1.0 Trait

#This file is located at traits/create.raml

responses:
  201:
    description: Created
    headers:
      Location:
        example: http://xxx/Condidition/123/_history/1
      Last-Modified: datetime
      ETag:
        example: '1.0'
