#%RAML 1.0 Trait

#This file is located at traits/history.raml

queryParameters:
  _count:
    required: false
  _since:
    required: false
responses:
  200:
    body:
      application/json:
        type: <<bundleName>>
