#%RAML 1.0 Trait

#This file is located at traits/update.raml

responses:
  200:
    description: Updated
  201:
    description: Created
    headers:
      Location:
        example: http://xxx/condidition/123/_history/1
      Last-Modified: datetime
      ETag:
        example: '1.0'
  422:
    description: |
      Unprocessable Entity - the proposed resource violated applicable FHIR profiles or server business rules

