#%RAML 1.0 DataType

#This file is located at dataTypes/elements/HumanName.raml

type: Element
properties:
  use?:
    type: code
    enum: [usual, official ,temp, nickname, anonymous, old, maiden]
  text?:
  family?: string[]
  given?: string[]
  prefix?: string[]
  suffix?: string[]
  period?: Period
