#%RAML 1.0 DataType

#This file is located at dataTypes/elements/SampledData.raml

description: A series of measurements taken by a device
type: Element
properties:
  origin: SimpleQuantity
  period: decimal
  factor?: decimal
  lowerLimit?: decimal
  upperLimit?: decimal
  dimensions: positiveInt
  data: string
