#%RAML 1.0 ResourceType

#This file is located at resourceTypes/fhirSearch.raml

post:
  description: This interaction searches a set of resources based on some filter criteria.
  body:
    application/x-www-form-urlencoded:
      properties: !include ../queryParams/searchParams.yaml
  responses:
    200:
      body:
        application/json:
          type: <<bundleName>>
get:
  description: This interaction searches a set of resources based on some filter criteria.
#  is: [{search: { bundleName: <<bundleName>>}}]
#  is: [search]
  responses:
    200:
      body:
        application/json:
          type: <<bundleName>>
