#%RAML 1.0 ResourceType

#This file is located at resourceTypes/fhirResource.raml

get:
  description: The read interaction accesses the current contents of a resource.
  is: [read]
  responses:
    200:
      body:
        application/json:
          type: <<resourcePathName|!singularize>>
          example: <<getSingleExample>>
put:
  description: The update interaction creates a new current version for an existing resource or creates an initial version if no resource already exists for the given id.
  is: [update]
  body:
    application/json:
      type: <<resourcePathName|!singularize>>
      example: <<putExample>>
delete:
  description: The delete interaction removes an existing resource.
  is: [delete]
