#%RAML 1.0 DataType

#This file is located at dataTypes/resources/AllergyIntolerance.raml

type: DomainResource
properties:
  identifier?: Identifier[]
  onset?: dateTime
  recordedDate?: dateTime
  recorder?: Reference
  patient: Reference
  reporter?: Reference
  substance: CodeableConcept
  status?:
    type: code
    enum: [active, unconfirmed, confirmed, inactive, resolved, refuted, entered-in-error]
  criticality?:
    type: code
    enum: [CRITL, CRITH, CRITU]
  type?:
    type: code
    enum: [allergy, intolerance]
  category?:
    type: code
    enum: [food, medication, environment, other]
  lastOccurence?: dateTime
  note?: Annotation
  reaction?:
    type: array
    items:
      type: BackboneElement
      properties:
        substance?: CodeableConcept
        certainty?:
          type: code
          enum: [unlikely, likely, confirmed]
        manifestation:
          type: array
          minItems: 1
          items:
            type: CodeableConcept
        description?: string
        onset?: dateTime
        severity?:
          type: code
          enum: [mild, moderate, severe]
        exposureRoute?: CodeableConcept
        note?: Annotation
