#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Device.raml

description: An instance of a manufactured te that is used in the provision of healthcare
type: DomainResource
properties:
  identifier?: Identifier[]
  type: CodeableConcept
  note?: Annotation[]
  status?:
    type: code
    enum: [available, not-available, enetered-in-error]
  manufacturer?: string
  model?: string
  version?: string
  manufactureDate?: dateTime
  expiry?: dateTime
  udi?: string
  lotNumber?: string
  owner?: Reference
  location?: Reference
  patient?: Reference
  contact?: ContactPoint[]
  url?: uri
