#%RAML 1.0 DataType

#This file is located at dataTypes/resources/MedicationOrder.raml

type: DomainResource
properties:
  identifier?: Identifier[]
  dateWritten?: dateTime
  status?:
    type: code
    enum: [active, on-hold, completed, entered-in-error, stopped, draft]
  dateEnded?: dateTime
  reasonEnded?: CodeableConcept
  patient?: Reference
  prescriber?: Reference
  encounter?: Reference
  /^reason(CodeableConcept|Reference)$/?: CodeableConcept | Reference
  note?: string
  /^medication(CodeableConcept|String)$/: CodeableConcept | string
  dosageInstruction?:
    type: array
    items:
      type: BackboneElement
      properties:
        text?:
        additionalInstructions?: CodeableConcept
        timing?: Timing
        /^asNeeded(Boolean|CodeableConcept)$/?: boolean | CodeableConcept
        /^site(CodeableConcept|Reference)$/?: CodeableConcept | Reference
        route?: CodeableConcept
        method?: CodeableConcept
        /^dose(Range|Quantity)$/?: Range | Quantity
        /^rate(Ratio|Range)$/?: Ratio | Range
        maxDosePerPeriod?: Ratio
  dispenseRequest?:
    type: BackboneElement
    properties:
      /^medication(CodeableConcept|Reference)$/: CodeableConcept | Reference
      validityPeriod?: Period
      numberOfRepeatsAllowed?: positiveInt
      quantity?: SimpleQuantity
      expectedSupplyDuration?: Duration
  substitution?:
    type: BackboneElement
    properties:
      type?: CodeableConcept
      reason?: CodeableConcept
  priorPrescription?: Reference
