#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Observation.raml

type: DomainResource
properties:
  identifier?: Identifier[]
  status: ObservationStatus
  category?: CodeableConcept
  code: CodeableConcept
  subject?: Reference
  encounter?: Reference
  /^effective(DateTime|Period)$/?: dateTime | Period
  issued?: instant
  performer?: Reference[]
  /^value(Quantity|CodeableConcept|String|Range|Ratio|SampledData|Attachment|Time|DateTime|Period)$/?: Quantity | CodeableConcept | string | Range | Ratio | SampledData | Attachment |  time | dateTime | Period
  dataAbsentReason?: CodeableConcept
  interpretation?: CodeableConcept
  comments?: string
  bodySite?: CodeableConcept
  method?: CodeableConcept
  specimen?: Reference
  device?: Reference
  referenceRange?:
    type: array
    items:
      type: BackboneElement
      properties:
        low?: SimpleQuantity
        high?: SimpleQuantity
        meaning?: CodeableConcept
        age?: Range
        text?: string
  related?:
    type: array
    items:
      type: BackboneElement
      properties:
        type?: ObservationRelationshipType
        target: Reference
  component?:
    type: array
    items:
      type: BackboneElement
      properties:
        code: CodeableConcept
        /^value(Quantity|CodeableConcept|String|Range|Ratio|SampledData|Attachment|Time|DateTime|Period)$/?: Quantity | CodeableConcept | string | Range | Ratio | SampledData | Attachment | time | dateTime | Period
        dataAbsentReason?: CodeableConcept
        referenceRange?:
          type: array
          items:
            type: BackboneElement
            properties:
              low?: SimpleQuantity
              high?: SimpleQuantity
              meaning?: CodeableConcept
              age?: Range
              text?: string
