#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Questionnaire.raml

type: DomainResource
properties:
  status:
    type: code                               # R!  draft | active | retired | unknown
    enum: [draft, active, retired, unknown]
  approvalDate?: date                        # When the questionnaire was approved by publisher
  code?: Coding[]                            # Concept that represents the overall questionnaire
  contact?: ContactDetail[]                  # Contact details for the publisher
  copyright?: markdown                       # Use and/or publishing restrictions
  date?: dateTime                            # Date this was last changed
  description?: markdown                     # Natural language description of the questionnaire
  effectivePeriod?: Period                   # When the questionnaire is expected to be used
  experimental?: boolean                     # For testing purposes, not real usage
  identifier?: Identifier[]                  # Additional identifier for the questionnaire
  item?: QuestionnaireItem[]                 # Questions and sections within the Questionnaire
  jurisdiction?: CodeableConcept[]           # Intended jurisdiction for questionnaire (if applicable)
  lastReviewDate?: date                      # When the questionnaire was last reviewed
  name?: string                              # Name for this questionnaire (computer friendly)
  publisher?: string                         # Name of the publisher (organization or individual)
  purpose?: markdown                         # Why this questionnaire is defined
  subjectType?: code[]                       # Resource that can be subject of QuestionnaireResponse
  title?: string                             # Name for this questionnaire (human friendly)
  url?: uri                                  # Logical URI to reference this questionnaire (globally unique)
  useContext?: UsageContext[]                # Context the content is intended to support
  version?: string                           # Business version of the questionnaire
