#%RAML 1.0 DataType

#This file is located at dataTypes/resources/QuestionnaireResponse.raml

type: DomainResource
properties:
  status:                             # R!  in-progress | completed | amended | entered-in-error | stopped
    type: code
    enum: [amended, completed, entered-in-error, in-progress, stopped]
  identifier?: Identifier             # Unique id for this set of answers
  basedOn?: Reference[]               # Request fulfilled by this QuestionnaireResponse
  parent?: Reference[]                # Part of this action
  questionnaire?: Reference           # Form being answered
  subject?: Reference                 # The subject of the questions
  context?: Reference                 # Encounter or Episode during which questionnaire was completed
  authored?: dateTime                 # Date the answers were gathered
  author?: Reference                  # Person who received and recorded the answers
  source?: Reference                  # The person who answered the questions
  item?: QuestionnaireResponseItem[]  # Groups and questions

