#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Schedule.raml

description: |
  A container for slot(s) of time that may be available for booking appointments
type: DomainResource
properties:
  identifier?: Identifier[]
  type?: CodeableConcept[]
  actor: Reference
  planningHorizon?: Period
  comment?: string
