#%RAML 1.0 DataType

#This file is located at dataTypes/resources/Slot.raml

description: |
  A slot of time on a schedule that may be available for booking appointments
type: DomainResource
properties:
  identifier?: Identifier[]
  type?: CodeableConcept
  schedule: Reference
  freeBusyType:
    type: code
    enum: [busy, free, busy-unavailable, busy-tentative]
  start: instant
  end: instant
  overbooked?: boolean
  comment?: string
