#%RAML 1.0 DataType

#This file is located at dataTypes/bundles/Bundle.raml

#not to be used directly - use more specific types: GeneralBundle or <resourceName>Bundle
type: Resource
properties:
  resourceType?: string
  type:
    type: code
    enum: [document, message, transaction, transaction-response, batch, batch-response, history, searchset, collection]
  total?: unsignedInt
  link?:
    type: array
    items:
      type: BackboneElement
      properties:
        relation: string
        url: uri
  signature?: Signature
