#%RAML 1.0 DataType

#This file is located at dataTypes/bundles/GeneralBundle.raml

type: Bundle
properties:
  entry?:
    type: array
    items:
      type: BackboneElement
      properties:
        link?:
          type: array
          items:
            type: BackboneElement
            properties:
              relation: string
              url: uri
        fullUrl?: uri
        resource?: Resource
        search?:
          type: BackboneElement
          properties:
            mode?:
              type: code
              enum: [match, include, outcome]
            score?: decimal
        request?:
          type: BackboneElement
          properties:
            method:
              type: code
              enum: [GET, PUT, POST, DELETE]
            url: uri
            ifNoneMatch?: string
            ifModifiedSince?: instant
            ifMatch: string
            ifNoneExist: string
        response?:
          type: BackboneElement
          properties:
            status: string
            location?: uri
            etag?: string
            lastModified?: instant
