name: GitHub CI

on: [push, pull_request]

jobs:
  npm:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        # exclude:
        #   - os: windows-latest
        #     node-version: 13.x
    steps:
      - run: git config --global core.autocrlf false # this is needed to prevent git changing EOL after cloning on Windows OS
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install with npm
        run: |
          npm install
      - name: Lint code
        run: |
          npm run lint
      - name: Build
        run: |
          npm run build:all
      - name: Run tests
        run: |
          npm run test:ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info
